### ISSUE TITLE
Awaken 2021 (instead of Merch) updates

### ISSUE THREAD

**Issue by frizman21** [watermarkchurch/theporch-apollos#115]
### Main navigation
- [x] icon on main navigation (bottom) from shirt to a heart symbol. (Allison to provide)
- [x] "MERCH" to "AWAKEN"

### Merch Storage Page
- [ ] Replace "MERCH STORE" art (with girl wearing "The Porch" long sleeve t-shirt) with... (allison to provide)
- [ ] "Shop Now" button replaced with "Awaken 2021"
- [ ] Touch "Shop Now", it should go to https://www.theporch.live/awaken instead of https://shop.theporch.live

**Comment by jpowell** [comment]
These updates are o.b.e.
