### ISSUE TITLE
update images for awaken

### ISSUE THREAD

**Issue by jpowell** [watermarkchurch/theporch-apollos#190]
Update Assets:
- tab icon svg
- screen hero image

![IMG_5212](https://user-images.githubusercontent.com/35932/184241144-b7c52685-4c39-40ea-a773-8d711eb08065.jpeg)

[Awaken-2022-images.zip](https://github.com/watermarkchurch/theporch-apollos/files/9310259/Awaken-2022-images.zip)

**Comment by jpowell** [comment]
@gburgett did you get the assets from the porch team for this?

**Comment by jpowell** [comment]
Kicked to Apollos team

**Comment by skipperpickle** [comment]
Updated images:
[Awaken-2022-images.zip](https://github.com/watermarkchurch/theporch-apollos/files/9310259/Awaken-2022-images.zip)

**Comment by nlewis84** [comment]
@jpowell Update incoming.

<img src="https://user-images.githubusercontent.com/72768221/184380704-70f629e2-0d89-402f-8f18-1e2c37e1e1b4.png" width="50%" />

**Comment by vinnyjth** [comment]
Done by Apollos Team
