### ISSUE TITLE
Migrate campus list to use WMR location index

### ISSUE THREAD

**Issue by jpowell** [watermarkchurch/theporch-apollos#203]
### User Story
As a USER, I want to see campuses powered by algolia, not Rock

Goal: remove dependency on the porch rock instance for location / campus data

### Problem statement
Move campus list data source from Rock to Algolia index

### Changes to make
- [ ] use algolia index for location list
- [ ] remove rock dependency
- [ ] support only one location link since new data source only has one `website` link (currently, as many as 3 are supported including socials)

##### Use Algolia index:
- App ID: FPTWE3M1PT
- index: wmresources_heroku_production_ministry_locations
- Facet to filter to the porch: `ministry: The Porch Live` ([filter docs](https://www.algolia.com/doc/api-reference/api-parameters/filters/)
- See ministry object schema below
- Ask for algolia api access key from Watermark Dev

##### Remove Rock dependency
- If no other use for Rock is present in the codebase, then remove dependency on Rock entirely

#### Relevant Information / Research / Back story
The porch website uses a different data source for campus / location list, and this is more accurate for current process.

##### Ministry Location Example Schema:

```json
{
  "address": {
    "street1": "4255 Ashland Avenue",
    "city": "Cincinnati",
    "country": "United States",
    "state": "Ohio",
    "zip": "45212",
    "street2": ""
  },
  "locationDisplayName": "",
  "contact": {
    "name": "",
    "email": "ColbyLtaylor01@gmail.com",
    "phone": ""
  },
  "description": "",
  "hasChildcare": false,
  "launchDate": null,
  "meetingDay": "Tuesday",
  "meetingTime": "7:00 PM",
  "ministry": "The Porch Live",
  "thumbnailUrl": "https://www.watermarkresources.com/accounts/1703/logo",
  "title": "Ashland Avenue Baptist Church",
  "trainingLocation": false,
  "website": "https://www.theporch.live/",
  "places": [
    "Cincinnati",
    "Hamilton County",
    "Ohio",
    "United States",
    "45212"
  ],
  "has_spanish": false,
  "_geoloc": {
    "lat": 39.1557554,
    "lng": -84.45808099999999
  },
  "objectID": "6241"
}
```

**Comment by gburgett** [comment]
@skipperpickle please figure out who we need to contact on the Porch team to ensure we are communicating the impact of this change to their workflow when they manage porch live locations

**Comment by jpowell** [comment]
Sam Scott is in the know - he just said to let them know when it shifts. I hadn’t prioritized yet because we could kick it to apollos team and not do it on our time.


Justin Powell
Director of External Technology Development
214-393-3023 | Schedule a meeting with me<https://calendly.com/_jpowell>
watermark.org<https://watermark.org>


[cid:wmgraphic_b1ac8bcd-e917-4e20-8c1d-29178aaf6041.png]



________________________________

**Comment by jpowell** [comment]
@gburgett did you see my note in response about Apollos team doing it??

**Comment by gburgett** [comment]
I missed that, Thanks!

**Comment by jpowell** [comment]
Update on these requirements: Porch team has agreed to remove locations / campuses from the app altogether. Instead, we will render a link that opens to the locations page on the website.
