### ISSUE TITLE
Upgrade to Redis 6 before 30 May 2023

### ISSUE THREAD

**Issue by gburgett** [watermarkchurch/theporch-apollos#205]
Heroku is requiring redis upgrades.  Upgrade the graphql server to Redis 6.

Instructions for connecting to Redis 6 are here: https://devcenter.heroku.com/articles/connecting-heroku-redis#connecting-in-node-js

Reference PR: https://github.com/watermarkchurch/paper-signs/pull/3105

**Comment by jpowell** [comment]
Apollos team is working this
